### ISSUE TITLE
Cannot reproduce results

### ISSUE THREAD

**Issue by chetankm1992** [bowenliu16/rl_graph_generation#9]
After running for 12 days with 64 CPU's and few available GPU's (which I guess were not used by this method) finally this method finished training. It has generated a number of molecules over each iteration. When trying to generate the results using given evaluation code (which first needed to fixed for test data, authors just used sample of training data for evaluation), the results are different from training set with no improvement and less than input data statistics.
Tried to get the values for penalized logP (trained model with conditions=True and has_scaffold=True) using given reward_penalized_logp function in molecule.py and checked the top 3 largest values which has maximum of 3.34 and when checked minimum that is -89.43 which are nowhere near as reported in paper.
Either full code is not given for training or the evaluation is done differently for which code is not provided. I don't know how I can get the same results in in paper.

**Comment by JiaxuanYou** [comment]
Hi, thanks for raising the issue.

**Comment by JiaxuanYou** [comment]
Hi, thanks for raising the issue. We release the code for our project in order to illuminate future research, but did not release the full specification for each experiment. As you can see, there are many hyperparameters there, and you can tune them to get similar or even better results. Some suggestions include "--logp_ratio", "--gan_final_ratio", "layer_num_g", "layer_num_d", "gcn_aggregate", etc. Unfortunately we didn't keep all the arguments in an easy-to-share way, we only kept the generated results.
